### ISSUE TITLE
`Serializable` needs to be reflective

### ISSUE THREAD

**Issue by jasoncorso** [voxel51/eta#114]
We need everything in eta that is written via json to be reflective.  This would enhance and simplify overall functionality.

I also think we should deprecate `from_json` and `write_json` to just `read` and `write`.

**Comment by brimoor** [comment]
It would be easy to update `Serializable` to do this (even optionally, say), but we should be aware that:
(a) it would bloat the size of all our JSON files. For example, it would almost double the size of low-level objects like `RelativePoint`, 
(b) it would encourage developers to try to duck-type everything and write all kinds of modules that work with various objects, which seems like a recipe for disaster.

**Comment by jasoncorso** [comment]
(a) If we storage size was a high priority, we would not be using json.
(b) I don't see how that would be a direct or event natural result.

**Comment by jasoncorso** [comment]
(b2) But, even if I don't see it is a natural result, I think we want to
seriously consider Serializable reflectiveness for its benefits and
explicitly frown upon this stated practice in the dev-guide.

An alternative is to inject a class in this middle (ReflectiveSerializable)
or something like that and use it carefully.  But I don't know...  I lean
toward all-things-Serializable-are-reflective.  To me, that is the notion
of Serializable --- it can be unserialized without any outside knowledge.
