### ISSUE TITLE
Make eta.core.utils.parse_dir_* methods into builder methods of DataFileSequence

### ISSUE THREAD

**Issue by brimoor** [voxel51/eta#121]
Methods like `eta.core.utils.parse_dir_pattern` and `eta.core.utils.parse_bounds_from_dir_pattern` should be converted into builder methods of `eta.core.data.DataFileSequence`, which should be our one-stop shop for all file-sequence-related operations.

(I like `eta.core.data.DataFileSequence` --- this idea has been sorely missing)

**Comment by jasoncorso** [comment]
I solved this quickly by adding the two build methods and just calling the appropriate functions from utils.  My preference is to leave the general functionality in utils as it may be useful elsewhere.
