### ISSUE TITLE
`examples/demo_video_pipeline` needs to be updated

### ISSUE THREAD

**Issue by jasoncorso** [voxel51/eta#359]
The example called `demo_video_pipeline` uses the old style of specifying the pipeline and should be updated to use the new one to avoid confusion.  Or at least to include both.
Or perhaps it should point to the `demo_video_clipper` as the example for the new form of the pipelines (with new links into where the files actually live).

**Comment by brimoor** [comment]
`demo_video_pipeline ` is there for completeness as an example of running a manually constructed pipeline. I'm onboard with linking to the other examples from `examples/demo_video_pipeline/README.md` though, just to make it clear that this isn't the recommended way to do things. 

The `examples/README.md` puts this in context:

Run a pre-configued video processing pipeline:

```shell
eta run demo_video_pipeline/pipeline.json
```

Build and run pipelines from requests:

```shell
eta build -r demo_video_formatter/request.json --run-now
eta build -r demo_video_clipper/request.json --run-now
```

**Comment by jasoncorso** [comment]
Yep, needs more fleshing out if the new user is to be able to understand it without pulling out her or his hair.

**Comment by brimoor** [comment]
https://github.com/voxel51/eta/pull/360
