### ISSUE TITLE
The ETA type system needs to let me create project-specific types

### ISSUE THREAD

**Issue by jasoncorso** [voxel51/eta#364]
As far as I can tell (by trying it), I cannot create a type outside of the main `eta.core.types` module.  I think this should be configurable as an ETA `config.json` type variable.

**Comment by brimoor** [comment]
From the `eta.core.types` module docstring:
> More types may be defined in other modules, but they must inherit from the
> base type `eta.core.types.Type` defined here.

When you try to use a custom type, your environment will have to be setup such that the type string you put in your module --- eg, `"your.custom.module.Type"` can be correctly interpreted by `eta.core.types.parse_type()`, which uses `eta.core.utils.get_class()` under-the-hood
