### ISSUE TITLE
Sample select frames problem

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/eta#446]
There seems to be an issue when using `sample_select_frames` in `eta.core.video` and setting `fast=False`. I am getting videos that look like this. 
![test (copy)](https://user-images.githubusercontent.com/21222883/75821973-2746ef00-5d6d-11ea-814a-e5d07fdd68d3.png)

When I sample with `fast=True` it returns the expected output.
![test](https://user-images.githubusercontent.com/21222883/75821972-26ae5880-5d6d-11ea-9833-b5f31c20b0ce.png)

**Comment by brimoor** [comment]
I had the same observation today when working with a BDD video in `.mov` format. This was the impetus for https://github.com/voxel51/eta/pull/445.

Run this on your video (using the latest `eta:develop`):

```py
video_path = "/path/to/video.mov"
etav.VideoMetadata.build_for(video_path, verbose=True)
```

I get this:

```
...
    "width": 720,
    "height": 1280,
...
Extracted video metadata: {
    "frame_size": [
        720,
        1280
    ],
    "frame_rate": 30.08854221566354,
    "total_frame_count": 1903,
    "duration": 63.246667,
    "size_bytes": 32841746,
    "mime_type": "video/quicktime",
    "encoding_str": "avc1"
}
```

The problem is that `FFmpegVideoReader` (which uses `ffprobe` internally) is confused and thinks the width and height of the video is reversed......

**Comment by brimoor** [comment]
Here's where the stream info for the video is read: https://github.com/voxel51/eta/blob/d545e32f7b888f396fc089de1d2b6c489117a53d/eta/core/video.py#L2698

And here's where it's used to determine the frame size: https://github.com/voxel51/eta/blob/d545e32f7b888f396fc089de1d2b6c489117a53d/eta/core/video.py#L2516

If anyone can figure out a solution to this, please do!!!!!!!!!!!

**Comment by brimoor** [comment]
Here's a test video that exhibits the problem:

```
# Downloads to your working directory
eta gdrive download 1izpoUwMDPsmJMbyKzTgGmkoSgBk0a2IQ bdd100k_dd5e0167-fe59b827.mov
```

**Comment by benjaminpkane** [comment]
https://stackoverflow.com/questions/53339787/ffmpeg-get-orientation-inverted

Rotate is part of the metadata.
![Screenshot from 2020-03-03 18-41-37](https://user-images.githubusercontent.com/19821840/75830384-b577a100-5d7e-11ea-91f2-8daa6ba39c18.png)

**Comment by brimoor** [comment]
ooooooooooohhhhhhhh. thanks!
