### ISSUE TITLE
Read images from URLs

### ISSUE THREAD

**Issue by jasoncorso** [voxel51/eta#449]
After using `skimage` for a while, I grew appreciative of their image reading function, which can handle web-urls for images.  I think this simple functionality would be a great feature addition to `eta.core.image`.

**Comment by brimoor** [comment]
https://github.com/voxel51/eta/pull/450 reminded me that I added `eta.core.image.download()` for that purpose a couple years ago. Obviously supporting that directly in `eta.core.image.read()` will make it easier to discover. Thanks @benjaminpkane!
