### ISSUE TITLE
[Discussion] Remove `Sphinx` dependency

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/eta#513]
`Sphinx` is currently a dependency and used in `eta.core.metadata`. From what I gather, it comes down to removing `--metadata` and `--refresh-metadata` flags in the `eta modules` command, or at least changing there implementations. Or, possibly creating a new `extras` requirement, which would still involve and implementation change.

Removing this dependency would lighten `voxel51-eta` installs, and therefore `fiftyone` installs, as well.

**Comment by brimoor** [comment]
Ah thanks for tracking this down.

Given that ETA's primary use is currently as a utils library and the pipeline stuff isn't required for that, I think including an install extra, say `pip install voxel51-eta[pipeline]` that includes pipeline-specific things like this makes sense.

Or in the name of speed, I could just convert the Sphinx import to a `lazy_import()` that will tell the user JIT what to install if they want to use pipelines.
