### ISSUE TITLE
Functionality to query/list available modules and pipelines on the path

### ISSUE THREAD

**Issue by jasoncorso** [voxel51/eta#62]
A new-to-ETA developer will want to get acquainted with the available functionality out of the box.  A seasoned-ETA developer will want to learn what new modules or pipelines may have been added recently.  A pipeline developer will need to list available modules. 

ETA needs an `apt-cache`-like functionality to navigate the module and pipeline space.

**Comment by brimoor** [comment]
See https://github.com/voxel51/eta/pull/133.

```shell
eta modules --list
eta pipelines --list
```

and many more things now exist.
